run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - misspell
    - bodyclose



issues:
  max-issues-per-linter: 0
  max-same-issues: 0


