run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - revive
    - goimports
    - misspell
    - bodyclose

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true # Disable for MVP to avoid too many comments

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
