version: 2

project_name: go-send

builds:
  - id: client
    main: ./cmd/client
    binary: go-send
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

  - id: server
    main: ./cmd/server
    binary: go-send-server
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    # go-send_1.0.0_linux_amd64.tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms:
  - id: client-pkg
    package_name: go-send
    builds:
      - client
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    vendor: VinMeld
    homepage: https://github.com/VinMeld/go-send
    maintainer: Vinay <vinaymeldrum@gmail.com>
    description: Secure file transfer tool (Client)
    license: GPLv3
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin

  - id: server-pkg
    package_name: go-send-server
    builds:
      - server
    file_name_template: "{{ .ProjectName }}-server_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    vendor: VinMeld
    homepage: https://github.com/VinMeld/go-send
    maintainer: Vinay <vinaymeldrum@gmail.com>
    description: Secure file transfer tool (Server)
    license: GPLv3
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    contents:
      - src: ./packaging/systemd/go-send-server.service
        dst: /usr/lib/systemd/system/go-send-server.service
        file_info:
          mode: 0644

aurs:
  - name: go-send-bin
    homepage: https://github.com/VinMeld/go-send
    description: Secure file transfer tool with challenge-response authentication (Binary)
    maintainers:
      - "Vinay <vinaymeldrum@gmail.com>"
    license: "GPL-3.0"
    private_key: '{{ .Env.AUR_SSH_KEY }}'
    git_url: 'ssh://aur@aur.archlinux.org/go-send-bin.git'
    conflicts:
      - go-send
      - go-send-git
    provides:
      - go-send
    package: |-
      # bin
      install -Dm755 "./go-send" "${pkgdir}/usr/bin/go-send"

      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/go-send/LICENSE"
