package server

import (
	"bytes"
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"os"
	"testing"

	"github.com/VinMeld/go-send/internal/models"
)

func setupTestServer(t *testing.T) (*Handler, *Storage, string) {
	tmpDir, err := os.MkdirTemp("", "go-send-handler-test")
	if err != nil {
		t.Fatal(err)
	}

	blobStore := NewLocalBlobStore(tmpDir)
	store, err := NewStorage(tmpDir, blobStore)
	if err != nil {
		t.Fatal(err)
	}

	return NewHandler(store), store, tmpDir
}

func TestPingHandler(t *testing.T) {
	h, _, tmpDir := setupTestServer(t)
	defer func() { _ = os.RemoveAll(tmpDir) }()

	req := httptest.NewRequest("GET", "/ping", nil)
	w := httptest.NewRecorder()

	h.Ping(w, req)

	if w.Code != http.StatusOK {
		t.Errorf("Expected status 200, got %d", w.Code)
	}
	if w.Body.String() != "pong" {
		t.Errorf("Expected body 'pong', got %s", w.Body.String())
	}
}

func TestRegisterUserHandler(t *testing.T) {
	h, _, tmpDir := setupTestServer(t)
	defer func() { _ = os.RemoveAll(tmpDir) }()

	user := models.User{
		Username:          "alice",
		IdentityPublicKey: make([]byte, 32),
		ExchangePublicKey: make([]byte, 32),
	}
	data, _ := json.Marshal(user)
	req := httptest.NewRequest("POST", "/users", bytes.NewBuffer(data))
	w := httptest.NewRecorder()

	h.RegisterUser(w, req)

	if w.Code != http.StatusCreated {
		t.Errorf("Expected status 201, got %d", w.Code)
	}

	// Verify user was added
	reqGet := httptest.NewRequest("GET", "/users?username=alice", nil)
	wGet := httptest.NewRecorder()
	h.GetUser(wGet, reqGet)

	if wGet.Code != http.StatusOK {
		t.Errorf("Expected status 200 for GetUser, got %d", wGet.Code)
	}
}

func TestHandlerErrors(t *testing.T) {
	h, _, tmpDir := setupTestServer(t)
	defer func() { _ = os.RemoveAll(tmpDir) }()

	// Test Register User - Bad Body
	req := httptest.NewRequest("POST", "/users", bytes.NewBuffer([]byte("bad json")))
	w := httptest.NewRecorder()
	h.RegisterUser(w, req)
	if w.Code != http.StatusBadRequest {
		t.Errorf("Expected 400 for bad json, got %d", w.Code)
	}

	// Test Get User - Missing Param (Should list users)
	req = httptest.NewRequest("GET", "/users", nil)
	w = httptest.NewRecorder()
	h.GetUser(w, req)
	if w.Code != http.StatusOK {
		t.Errorf("Expected 200 for missing username (list users), got %d", w.Code)
	}

	// Test Upload File - Bad Body
	req = httptest.NewRequest("POST", "/files", bytes.NewBuffer([]byte("bad json")))
	w = httptest.NewRecorder()
	h.UploadFile(w, req)
	if w.Code != http.StatusBadRequest {
		t.Errorf("Expected 400 for bad json, got %d", w.Code)
	}

	// Test Download File - Missing ID
	req = httptest.NewRequest("GET", "/files/download", nil)
	w = httptest.NewRecorder()
	h.DownloadFile(w, req)
	if w.Code != http.StatusBadRequest {
		t.Errorf("Expected 400 for missing id, got %d", w.Code)
	}
}

func TestUploadListFiles(t *testing.T) {
	h, store, tmpDir := setupTestServer(t)
	defer func() { _ = os.RemoveAll(tmpDir) }()

	// Register User
	user := models.User{
		Username:          "bob",
		IdentityPublicKey: make([]byte, 32),
		ExchangePublicKey: make([]byte, 32),
	}
	_ = store.AddUser(context.Background(), user)

	// Upload File
	meta := models.FileMetadata{
		ID: "file1", Sender: "alice", Recipient: "bob", FileName: "test.txt", EncryptedKey: []byte("key"),
	}
	reqBody := models.UploadRequest{
		Metadata:         meta,
		EncryptedContent: []byte("content"),
	}
	data, _ := json.Marshal(reqBody)
	req := httptest.NewRequest("POST", "/files", bytes.NewBuffer(data))
	w := httptest.NewRecorder()
	h.UploadFile(w, req)

	if w.Code != http.StatusCreated {
		t.Fatalf("Expected 201, got %d: %s", w.Code, w.Body.String())
	}

	// List Files
	req = httptest.NewRequest("GET", "/files?recipient=bob", nil)
	w = httptest.NewRecorder()
	h.ListFiles(w, req)

	if w.Code != http.StatusOK {
		t.Fatalf("Expected 200, got %d", w.Code)
	}

	var files []models.FileMetadata
	_ = json.NewDecoder(w.Body).Decode(&files)
	if len(files) != 1 {
		t.Fatalf("Expected 1 file, got %d", len(files))
	}

	// Capture the actual ID generated by server
	fileID := files[0].ID

	// Download File
	req = httptest.NewRequest("GET", "/files/download?id="+fileID, nil)
	w = httptest.NewRecorder()
	h.DownloadFile(w, req)

	if w.Code != http.StatusOK {
		t.Errorf("Expected 200, got %d", w.Code)
	}
}

func TestAutoDelete(t *testing.T) {
	h, store, tmpDir := setupTestServer(t)
	defer func() { _ = os.RemoveAll(tmpDir) }()

	// Register User
	user := models.User{
		Username:          "bob",
		IdentityPublicKey: make([]byte, 32),
		ExchangePublicKey: make([]byte, 32),
	}
	_ = store.AddUser(context.Background(), user)

	// Upload File with AutoDelete
	meta := models.FileMetadata{
		ID: "file1", Sender: "alice", Recipient: "bob", FileName: "secret.txt", AutoDelete: true, EncryptedKey: []byte("key"),
	}
	reqBody := models.UploadRequest{
		Metadata:         meta,
		EncryptedContent: []byte("burn after reading"),
	}
	data, _ := json.Marshal(reqBody)
	req := httptest.NewRequest("POST", "/files", bytes.NewBuffer(data))
	w := httptest.NewRecorder()
	h.UploadFile(w, req)

	if w.Code != http.StatusCreated {
		t.Fatalf("Expected 201, got %d: %s", w.Code, w.Body.String())
	}

	req = httptest.NewRequest("GET", "/files?recipient=bob", nil)
	w = httptest.NewRecorder()
	h.ListFiles(w, req)

	var files []models.FileMetadata
	_ = json.NewDecoder(w.Body).Decode(&files)
	if len(files) != 1 {
		t.Fatalf("Expected 1 file, got %d", len(files))
	}
	fileID := files[0].ID

	// Download File
	req = httptest.NewRequest("GET", "/files/download?id="+fileID, nil)
	w = httptest.NewRecorder()
	h.DownloadFile(w, req)

	if w.Code != http.StatusOK {
		t.Fatalf("Expected 200, got %d", w.Code)
	}

	// Verify Deletion
	if _, ok := store.GetFileMetadata(context.Background(), fileID); ok {
		t.Error("File metadata should be deleted")
	}
	if _, err := store.GetFileContent(fileID); err == nil {
		t.Error("File content should be deleted")
	}
}

func TestDeleteFile(t *testing.T) {
	h, store, tmpDir := setupTestServer(t)
	defer func() { _ = os.RemoveAll(tmpDir) }()

	// Setup: Alice sends file to Bob
	userAlice := models.User{Username: "alice", IdentityPublicKey: make([]byte, 32), ExchangePublicKey: make([]byte, 32)}
	userBob := models.User{Username: "bob", IdentityPublicKey: make([]byte, 32), ExchangePublicKey: make([]byte, 32)}
	_ = store.AddUser(context.Background(), userAlice)
	_ = store.AddUser(context.Background(), userBob)

	meta := models.FileMetadata{ID: "file1", Sender: "alice", Recipient: "bob", FileName: "test.txt", EncryptedKey: []byte("key")}
	_ = store.SaveFile(context.Background(), meta, []byte("content"))

	// Helper to make authenticated request
	makeDeleteReq := func(user string, fileID string) *http.Response {
		req := httptest.NewRequest("DELETE", "/files?id="+fileID, nil)
		// Inject user into context (simulating AuthMiddleware)
		ctx := context.WithValue(req.Context(), userContextKey, user)
		w := httptest.NewRecorder()
		h.DeleteFile(w, req.WithContext(ctx))
		return w.Result()
	}

	// Test 1: Sender can delete
	resp := makeDeleteReq("alice", "file1")
	_ = resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Errorf("Sender should be able to delete, got %d", resp.StatusCode)
	}

	// Re-create file for next test
	_ = store.SaveFile(context.Background(), meta, []byte("content"))

	// Test 2: Recipient can delete
	resp = makeDeleteReq("bob", "file1")
	_ = resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Errorf("Recipient should be able to delete, got %d", resp.StatusCode)
	}

	// Re-create file
	_ = store.SaveFile(context.Background(), meta, []byte("content"))

	// Test 3: Unauthorized user cannot delete
	resp = makeDeleteReq("eve", "file1")
	_ = resp.Body.Close()
	if resp.StatusCode != http.StatusForbidden {
		t.Errorf("Unauthorized user should not be able to delete, got %d", resp.StatusCode)
	}

	// Test 4: File not found
	resp = makeDeleteReq("alice", "unknown")
	_ = resp.Body.Close()
	if resp.StatusCode != http.StatusNotFound {
		t.Errorf("Unknown file should get 404, got %d", resp.StatusCode)
	}
}

func TestPing(t *testing.T) {
	h, _, tmpDir := setupTestServer(t)
	defer func() { _ = os.RemoveAll(tmpDir) }()

	req := httptest.NewRequest("GET", "/ping", nil)
	w := httptest.NewRecorder()
	h.Ping(w, req)

	if w.Code != http.StatusOK {
		t.Errorf("Expected 200, got %d", w.Code)
	}
	if w.Body.String() != "pong" {
		t.Errorf("Expected pong, got %s", w.Body.String())
	}
}

func TestServeHTTP(t *testing.T) {
	h, _, tmpDir := setupTestServer(t)
	defer func() { _ = os.RemoveAll(tmpDir) }()

	// Test Ping Route
	req := httptest.NewRequest("GET", "/ping", nil)
	w := httptest.NewRecorder()
	h.ServeHTTP(w, req)
	if w.Code != http.StatusOK {
		t.Errorf("ServeHTTP /ping failed, got %d", w.Code)
	}

	// Test NotFound
	req = httptest.NewRequest("GET", "/unknown", nil)
	w = httptest.NewRecorder()
	h.ServeHTTP(w, req)
	if w.Code != http.StatusNotFound {
		t.Errorf("ServeHTTP /unknown failed, got %d", w.Code)
	}

	// Test MethodNotAllowed
	req = httptest.NewRequest("PUT", "/users", nil)
	w = httptest.NewRecorder()
	h.ServeHTTP(w, req)
	if w.Code != http.StatusMethodNotAllowed {
		t.Errorf("ServeHTTP /users PUT failed, got %d", w.Code)
	}
}
