// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Challenge struct {
	Username  string    `json:"username"`
	Nonce     string    `json:"nonce"`
	CreatedAt time.Time `json:"created_at"`
}

type File struct {
	ID           string    `json:"id"`
	Sender       string    `json:"sender"`
	Recipient    string    `json:"recipient"`
	FileName     string    `json:"file_name"`
	EncryptedKey []byte    `json:"encrypted_key"`
	AutoDelete   bool      `json:"auto_delete"`
	Timestamp    time.Time `json:"timestamp"`
}

type Session struct {
	Token     string    `json:"token"`
	Username  string    `json:"username"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	Username          string    `json:"username"`
	IdentityPublicKey []byte    `json:"identity_public_key"`
	ExchangePublicKey []byte    `json:"exchange_public_key"`
	CreatedAt         time.Time `json:"created_at"`
}
