// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateChallenge(ctx context.Context, arg CreateChallengeParams) error
	CreateFile(ctx context.Context, arg CreateFileParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteChallenge(ctx context.Context, username string) error
	DeleteFile(ctx context.Context, id string) error
	DeleteSession(ctx context.Context, token string) error
	DeleteUser(ctx context.Context, username string) error
	GetChallenge(ctx context.Context, username string) (string, error)
	GetFile(ctx context.Context, id string) (File, error)
	GetSession(ctx context.Context, token string) (Session, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListAllUsers(ctx context.Context) ([]ListAllUsersRow, error)
	ListFiles(ctx context.Context, recipient string) ([]File, error)
}

var _ Querier = (*Queries)(nil)
