// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"time"
)

const createChallenge = `-- name: CreateChallenge :exec
INSERT INTO challenges (username, nonce)
VALUES (?, ?)
ON CONFLICT(username) DO UPDATE SET nonce = excluded.nonce
`

type CreateChallengeParams struct {
	Username string `json:"username"`
	Nonce    string `json:"nonce"`
}

func (q *Queries) CreateChallenge(ctx context.Context, arg CreateChallengeParams) error {
	_, err := q.exec(ctx, q.createChallengeStmt, createChallenge, arg.Username, arg.Nonce)
	return err
}

const createFile = `-- name: CreateFile :exec
INSERT INTO files (id, sender, recipient, file_name, encrypted_key, auto_delete, timestamp)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateFileParams struct {
	ID           string    `json:"id"`
	Sender       string    `json:"sender"`
	Recipient    string    `json:"recipient"`
	FileName     string    `json:"file_name"`
	EncryptedKey []byte    `json:"encrypted_key"`
	AutoDelete   bool      `json:"auto_delete"`
	Timestamp    time.Time `json:"timestamp"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) error {
	_, err := q.exec(ctx, q.createFileStmt, createFile,
		arg.ID,
		arg.Sender,
		arg.Recipient,
		arg.FileName,
		arg.EncryptedKey,
		arg.AutoDelete,
		arg.Timestamp,
	)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token, username, expires_at)
VALUES (?, ?, ?)
`

type CreateSessionParams struct {
	Token     string    `json:"token"`
	Username  string    `json:"username"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.exec(ctx, q.createSessionStmt, createSession, arg.Token, arg.Username, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (username, identity_public_key, exchange_public_key)
VALUES (?, ?, ?)
`

type CreateUserParams struct {
	Username          string `json:"username"`
	IdentityPublicKey []byte `json:"identity_public_key"`
	ExchangePublicKey []byte `json:"exchange_public_key"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.exec(ctx, q.createUserStmt, createUser, arg.Username, arg.IdentityPublicKey, arg.ExchangePublicKey)
	return err
}

const deleteChallenge = `-- name: DeleteChallenge :exec
DELETE FROM challenges
WHERE username = ?
`

func (q *Queries) DeleteChallenge(ctx context.Context, username string) error {
	_, err := q.exec(ctx, q.deleteChallengeStmt, deleteChallenge, username)
	return err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files
WHERE id = ?
`

func (q *Queries) DeleteFile(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteFileStmt, deleteFile, id)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE token = ?
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.exec(ctx, q.deleteSessionStmt, deleteSession, token)
	return err
}

const getChallenge = `-- name: GetChallenge :one
SELECT nonce FROM challenges
WHERE username = ? LIMIT 1
`

func (q *Queries) GetChallenge(ctx context.Context, username string) (string, error) {
	row := q.queryRow(ctx, q.getChallengeStmt, getChallenge, username)
	var nonce string
	err := row.Scan(&nonce)
	return nonce, err
}

const getFile = `-- name: GetFile :one
SELECT id, sender, recipient, file_name, encrypted_key, auto_delete, timestamp FROM files
WHERE id = ? LIMIT 1
`

func (q *Queries) GetFile(ctx context.Context, id string) (File, error) {
	row := q.queryRow(ctx, q.getFileStmt, getFile, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Sender,
		&i.Recipient,
		&i.FileName,
		&i.EncryptedKey,
		&i.AutoDelete,
		&i.Timestamp,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT token, username, expires_at, created_at FROM sessions
WHERE token = ? LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, token string) (Session, error) {
	row := q.queryRow(ctx, q.getSessionStmt, getSession, token)
	var i Session
	err := row.Scan(
		&i.Token,
		&i.Username,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT username, identity_public_key, exchange_public_key, created_at FROM users
WHERE username = ? LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, username string) (User, error) {
	row := q.queryRow(ctx, q.getUserStmt, getUser, username)
	var i User
	err := row.Scan(
		&i.Username,
		&i.IdentityPublicKey,
		&i.ExchangePublicKey,
		&i.CreatedAt,
	)
	return i, err
}

const listAllUsers = `-- name: ListAllUsers :many
SELECT username, identity_public_key, exchange_public_key
FROM users
ORDER BY username
`

type ListAllUsersRow struct {
	Username          string `json:"username"`
	IdentityPublicKey []byte `json:"identity_public_key"`
	ExchangePublicKey []byte `json:"exchange_public_key"`
}

func (q *Queries) ListAllUsers(ctx context.Context) ([]ListAllUsersRow, error) {
	rows, err := q.query(ctx, q.listAllUsersStmt, listAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllUsersRow
	for rows.Next() {
		var i ListAllUsersRow
		if err := rows.Scan(&i.Username, &i.IdentityPublicKey, &i.ExchangePublicKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFiles = `-- name: ListFiles :many
SELECT id, sender, recipient, file_name, encrypted_key, auto_delete, timestamp FROM files
WHERE recipient = ?
ORDER BY timestamp DESC
`

func (q *Queries) ListFiles(ctx context.Context, recipient string) ([]File, error) {
	rows, err := q.query(ctx, q.listFilesStmt, listFiles, recipient)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Sender,
			&i.Recipient,
			&i.FileName,
			&i.EncryptedKey,
			&i.AutoDelete,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
